#! /bin/sh

### BEGIN INIT INFO
# Provides:             kibana at startup, my_init from phusion. 
# Required-Start:       see /etc/init.d/kibana for more info 
# Required-Stop:        see /etc/init.d/kibana for more info 
# Short-Description:    You know, for search.
### END INIT INFO

set -e

#Source the lsb functions to perform the following operations
 . /lib/lsb/init-functions

log_daemon_msg "my_init is starting kibana"
/etc/init.d/kibana start

exit 0