#! /bin/sh

### BEGIN INIT INFO
# Provides:             elasticsearch at startup
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Short-Description:    You know, for search.
### END INIT INFO

set -e
/etc/init.d/elasticsearch start
exit 0